// Build data/areas{LEVEL}.js from out/assign{LEVEL}.csv (made by build-assign.mjs):
// dissolved area polygons + prefecture border lines (TopoJSON) and per-code metadata.
// Usage: node build-data.mjs 3   (or 4)
// The output is a plain <script> so the site also works when opened from file://.
import fs from 'fs';
import { execFileSync } from 'child_process';

const LEVEL = +(process.argv[2] || 3);
const tmp = `out/areas${LEVEL}.topo.json`;

// run mapshaper's CLI with node directly (no shell, so arguments keep their spaces)
execFileSync(process.execPath, [
  'node_modules/mapshaper/bin/mapshaper', '-i', 'raw/muni.topo.json', 'name=muni',
  '-join', `out/assign${LEVEL}.csv`, 'keys=N03_007,N03_007', 'string-fields=N03_007,ab',
  '-filter', 'ab != null',
  '-dissolve', 'ab', '+', 'name=areas',
  '-dissolve', 'N03_001', 'target=muni', '+', 'name=prefs',
  '-innerlines', 'target=prefs', '+', 'name=preflines',
  // simplify every layer together so area edges and prefecture lines stay aligned
  '-simplify', '40%', 'keep-shapes', 'target=*',
  '-o', tmp, 'format=topojson', 'quantization=20000', 'target=areas,preflines',
], { stdio: 'inherit' });

const assign = JSON.parse(fs.readFileSync(`out/assign${LEVEL}.json`, 'utf8'));
const muni = JSON.parse(fs.readFileSync('raw/muni.topo.json', 'utf8'));
const seen = new Set();
const meta = {};
for (const g of Object.values(muni.objects)[0].geometries) {
  const p = g.properties, ab = assign[p.N03_007];
  if (!ab || seen.has(p.N03_007)) continue;
  seen.add(p.N03_007);
  const m = meta[ab] ??= { prefs: [], subs: [], cities: [], towns: [] };
  if (!m.prefs.includes(p.N03_001)) m.prefs.push(p.N03_001);
  if (p.N03_001 === '北海道' && p.N03_002 && !m.subs.includes(p.N03_002)) m.subs.push(p.N03_002);
  const grp = p.N03_003 || '', name = p.N03_004 || '';
  let city = null;
  if (p.N03_001 === '東京都' && !grp && /区$/.test(name)) city = '東京23区';
  else if (/市$/.test(grp)) city = grp; // designated-city ward
  else if (/市$/.test(name)) city = name;
  if (city) { if (!m.cities.includes(city)) m.cities.push(city); }
  else if (!m.towns.includes(name)) m.towns.push(name);
}

const topo = fs.readFileSync(tmp, 'utf8');
const js = `// Generated by tools/build-data.mjs — do not edit by hand.
// Sources: 総務省「市外局番の一覧」(令和8年3月1日現在), 国土数値情報 N03 via smartnews-smri/japan-topography
window.AREA_DATA = window.AREA_DATA || {};
window.AREA_DATA[${LEVEL}] = { topo: ${topo}, meta: ${JSON.stringify(meta)} };
`;
fs.writeFileSync(`../data/areas${LEVEL}.js`, js);
console.log(`level ${LEVEL}: ${Object.keys(meta).length} areas, ${(js.length / 1024).toFixed(0)}KB`);
