// Build data/areas.js: dissolved topology + per-0AB metadata, loadable via <script> (works on file:// too)
import fs from 'fs';
const assign = JSON.parse(fs.readFileSync('out/assign.json', 'utf8'));
const topo = JSON.parse(fs.readFileSync('raw/muni.topo.json', 'utf8'));
const areaTopo = JSON.parse(fs.readFileSync('../data/areas.topo.json', 'utf8'));
const seen = new Set(); const meta = {};
for (const g of Object.values(topo.objects)[0].geometries) {
  const p = g.properties, ab = assign[p.N03_007];
  if (!ab || seen.has(p.N03_007)) continue; seen.add(p.N03_007);
  const m = meta[ab] ??= { prefs: [], subs: [], cities: [], towns: 0 };
  if (!m.prefs.includes(p.N03_001)) m.prefs.push(p.N03_001);
  if (p.N03_001 === '北海道' && p.N03_002 && !m.subs.includes(p.N03_002)) m.subs.push(p.N03_002);
  const grp = p.N03_003 || '', name = p.N03_004 || '';
  let city = null;
  if (p.N03_001 === '東京都' && !grp && /区$/.test(name)) city = '東京23区';
  else if (/市$/.test(grp)) city = grp;             // designated-city ward
  else if (/市$/.test(name)) city = name;
  if (city) { if (!m.cities.includes(city)) m.cities.push(city); } else m.towns++;
}
const js = `// Generated by tools/build-meta.mjs — do not edit by hand.
// Sources: 総務省「市外局番の一覧」(令和8年3月1日現在), 国土数値情報 N03 via smartnews-smri/japan-topography
window.AREA_TOPO = ${JSON.stringify(areaTopo)};
window.AREA_META = ${JSON.stringify(meta)};
`;
fs.writeFileSync('../data/areas.js', js);
fs.rmSync('../data/areas.topo.json');
console.log(Object.keys(meta).length, (js.length / 1024).toFixed(0) + 'KB');
for (const k of ['011', '03', '045', '098', '049', '04']) console.log(k, JSON.stringify(meta[k]));
